2021-10-13 11:45:55,236 INFO    MainThread:596 [wandb_setup.py:_flush():69] setting env: {}
2021-10-13 11:45:55,236 INFO    MainThread:596 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-13 11:45:55,237 INFO    MainThread:596 [wandb_init.py:_log_setup():342] Logging user logs to c:\Users\reese\OneDrive\Documents\University\EEE4022S\Workspace\Final-Year-Project\wandb\run-20211013_114555-2t67wb0s\logs\debug.log
2021-10-13 11:45:55,237 INFO    MainThread:596 [wandb_init.py:_log_setup():343] Logging internal logs to c:\Users\reese\OneDrive\Documents\University\EEE4022S\Workspace\Final-Year-Project\wandb\run-20211013_114555-2t67wb0s\logs\debug-internal.log
2021-10-13 11:45:55,244 INFO    MainThread:596 [wandb_init.py:init():375] calling init triggers
2021-10-13 11:45:55,245 INFO    MainThread:596 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-10-13 11:45:55,245 INFO    MainThread:596 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 1qsssn9q
2021-10-13 11:45:55,248 INFO    MainThread:596 [wandb_run.py:finish():1271] finishing run rees123/Resnet50 Regression/1qsssn9q
2021-10-13 11:45:55,637 INFO    MainThread:596 [jupyter.py:save_history():353] not saving jupyter history
2021-10-13 11:45:55,637 INFO    MainThread:596 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-10-13 11:45:55,637 INFO    MainThread:596 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-10-13 11:45:55,637 INFO    MainThread:596 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 0
2021-10-13 11:45:55,638 INFO    MainThread:596 [wandb_run.py:_restore():1543] restore
2021-10-13 11:45:55,681 INFO    MainThread:596 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 920
  total_bytes: 920
}

2021-10-13 11:45:56,112 INFO    MainThread:596 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 920
  total_bytes: 920
}

2021-10-13 11:45:57,025 INFO    MainThread:596 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 920
  total_bytes: 11488
}

2021-10-13 11:45:57,131 INFO    MainThread:596 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 920
  total_bytes: 11488
}

2021-10-13 11:45:57,243 INFO    MainThread:596 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 920
  total_bytes: 11488
}

2021-10-13 11:45:57,353 INFO    MainThread:596 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 920
  total_bytes: 11488
}

2021-10-13 11:45:57,465 INFO    MainThread:596 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 920
  total_bytes: 11488
}

2021-10-13 11:45:57,577 INFO    MainThread:596 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 920
  total_bytes: 11488
}

2021-10-13 11:45:57,687 INFO    MainThread:596 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11488
  total_bytes: 11488
}

2021-10-13 11:45:57,799 INFO    MainThread:596 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11488
  total_bytes: 11488
}

2021-10-13 11:45:57,911 INFO    MainThread:596 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11488
  total_bytes: 11488
}

2021-10-13 11:45:58,021 INFO    MainThread:596 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11488
  total_bytes: 11488
}

2021-10-13 11:45:58,133 INFO    MainThread:596 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11488
  total_bytes: 11488
}

2021-10-13 11:45:58,246 INFO    MainThread:596 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11488
  total_bytes: 11488
}

2021-10-13 11:45:58,358 INFO    MainThread:596 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11488
  total_bytes: 11488
}

2021-10-13 11:45:59,024 INFO    MainThread:596 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11488
  total_bytes: 11488
}

2021-10-13 11:45:59,140 INFO    MainThread:596 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11488
  total_bytes: 11488
}

2021-10-13 11:46:00,284 INFO    MainThread:596 [wandb_run.py:_show_summary():1848] rendering summary
2021-10-13 11:46:00,285 INFO    MainThread:596 [wandb_run.py:_show_history():1886] rendering history
2021-10-13 11:46:00,287 INFO    MainThread:596 [wandb_run.py:_show_files():1915] logging synced files
2021-10-13 11:46:00,309 INFO    MainThread:596 [wandb_init.py:init():424] starting backend
2021-10-13 11:46:00,309 INFO    MainThread:596 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-10-13 11:46:00,400 INFO    MainThread:596 [backend.py:ensure_launched():135] starting backend process...
2021-10-13 11:46:00,631 INFO    MainThread:596 [backend.py:ensure_launched():139] started backend process with pid: 15856
2021-10-13 11:46:00,662 INFO    MainThread:596 [wandb_init.py:init():429] backend started and connected
2021-10-13 11:46:00,687 INFO    MainThread:596 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-10-13 11:46:00,688 INFO    MainThread:596 [wandb_run.py:_label_probe_notebook():822] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-10-13 11:46:00,688 INFO    MainThread:596 [wandb_init.py:init():477] updated telemetry
2021-10-13 11:46:00,689 INFO    MainThread:596 [wandb_init.py:init():500] communicating current version
2021-10-13 11:46:03,314 WARNING MainThread:596 [wandb_init.py:init():795] interrupted
Traceback (most recent call last):
  File "C:\Users\reese\miniconda3\envs\final-year-project\lib\site-packages\wandb\sdk\wandb_init.py", line 775, in init
    run = wi.init()
  File "C:\Users\reese\miniconda3\envs\final-year-project\lib\site-packages\wandb\sdk\wandb_init.py", line 501, in init
    ret = backend.interface.communicate_check_version(
  File "C:\Users\reese\miniconda3\envs\final-year-project\lib\site-packages\wandb\sdk\interface\interface.py", line 791, in communicate_check_version
    result = self._communicate(rec)
  File "C:\Users\reese\miniconda3\envs\final-year-project\lib\site-packages\wandb\sdk\interface\interface.py", line 539, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\reese\miniconda3\envs\final-year-project\lib\site-packages\wandb\sdk\interface\interface.py", line 77, in get
    is_set = self._object_ready.wait(timeout)
  File "C:\Users\reese\miniconda3\envs\final-year-project\lib\threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Users\reese\miniconda3\envs\final-year-project\lib\threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
