2021-10-11 17:37:23,055 INFO    MainThread:17104 [wandb_setup.py:_flush():69] setting env: {}
2021-10-11 17:37:23,055 INFO    MainThread:17104 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-11 17:37:23,056 INFO    MainThread:17104 [wandb_init.py:_log_setup():342] Logging user logs to c:\Users\reese\OneDrive\Documents\University\EEE4022S\Workspace\Final-Year-Project\wandb\run-20211011_173723-1dyekvnq\logs\debug.log
2021-10-11 17:37:23,056 INFO    MainThread:17104 [wandb_init.py:_log_setup():343] Logging internal logs to c:\Users\reese\OneDrive\Documents\University\EEE4022S\Workspace\Final-Year-Project\wandb\run-20211011_173723-1dyekvnq\logs\debug-internal.log
2021-10-11 17:37:23,057 INFO    MainThread:17104 [wandb_init.py:init():375] calling init triggers
2021-10-11 17:37:23,057 INFO    MainThread:17104 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-10-11 17:37:23,057 INFO    MainThread:17104 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 219u1rnf
2021-10-11 17:37:23,058 INFO    MainThread:17104 [wandb_run.py:finish():1271] finishing run rees123/Resnet50 Regression/219u1rnf
2021-10-11 17:37:23,209 INFO    MainThread:17104 [jupyter.py:save_history():353] not saving jupyter history
2021-10-11 17:37:23,209 INFO    MainThread:17104 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-10-11 17:37:23,209 INFO    MainThread:17104 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-10-11 17:37:23,209 INFO    MainThread:17104 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 0
2021-10-11 17:37:23,210 INFO    MainThread:17104 [wandb_run.py:_restore():1543] restore
2021-10-11 17:37:23,955 INFO    MainThread:17104 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 921
  total_bytes: 921
}

2021-10-11 17:37:24,415 INFO    MainThread:17104 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 921
  total_bytes: 921
}

2021-10-11 17:37:24,726 INFO    MainThread:17104 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 921
  total_bytes: 3584
}

2021-10-11 17:37:24,842 INFO    MainThread:17104 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 921
  total_bytes: 3584
}

2021-10-11 17:37:24,954 INFO    MainThread:17104 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 921
  total_bytes: 3584
}

2021-10-11 17:37:25,066 INFO    MainThread:17104 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 921
  total_bytes: 3584
}

2021-10-11 17:37:25,179 INFO    MainThread:17104 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 921
  total_bytes: 3584
}

2021-10-11 17:37:25,291 INFO    MainThread:17104 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 921
  total_bytes: 3584
}

2021-10-11 17:37:25,403 INFO    MainThread:17104 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3584
  total_bytes: 3584
}

2021-10-11 17:37:25,514 INFO    MainThread:17104 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3584
  total_bytes: 3584
}

2021-10-11 17:37:25,626 INFO    MainThread:17104 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3584
  total_bytes: 3584
}

2021-10-11 17:37:25,737 INFO    MainThread:17104 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3584
  total_bytes: 3584
}

2021-10-11 17:37:25,850 INFO    MainThread:17104 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3584
  total_bytes: 3584
}

2021-10-11 17:37:25,962 INFO    MainThread:17104 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3584
  total_bytes: 3584
}

2021-10-11 17:37:26,394 INFO    MainThread:17104 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3584
  total_bytes: 3584
}

2021-10-11 17:37:26,507 INFO    MainThread:17104 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3584
  total_bytes: 3584
}

2021-10-11 17:37:27,601 INFO    MainThread:17104 [wandb_run.py:_show_files():1915] logging synced files
2021-10-11 17:37:27,607 INFO    MainThread:17104 [wandb_init.py:init():424] starting backend
2021-10-11 17:37:27,607 INFO    MainThread:17104 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-10-11 17:37:27,612 INFO    MainThread:17104 [backend.py:ensure_launched():135] starting backend process...
2021-10-11 17:37:27,697 INFO    MainThread:17104 [backend.py:ensure_launched():139] started backend process with pid: 7016
2021-10-11 17:37:27,697 INFO    MainThread:17104 [wandb_init.py:init():429] backend started and connected
2021-10-11 17:37:27,710 INFO    MainThread:17104 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-10-11 17:37:27,710 INFO    MainThread:17104 [wandb_run.py:_label_probe_notebook():822] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-10-11 17:37:27,710 INFO    MainThread:17104 [wandb_init.py:init():477] updated telemetry
2021-10-11 17:37:27,711 INFO    MainThread:17104 [wandb_init.py:init():500] communicating current version
2021-10-11 17:37:28,821 INFO    MainThread:17104 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-10-11 17:37:28,822 INFO    MainThread:17104 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-10-11 17:37:29,201 INFO    MainThread:17104 [wandb_init.py:init():540] starting run threads in backend
2021-10-11 17:37:29,261 INFO    MainThread:17104 [wandb_run.py:_console_start():1601] atexit reg
2021-10-11 17:37:29,262 INFO    MainThread:17104 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-10-11 17:37:29,263 INFO    MainThread:17104 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-10-11 17:37:29,264 INFO    MainThread:17104 [wandb_run.py:_redirect():1536] Redirects installed.
2021-10-11 17:37:29,265 INFO    MainThread:17104 [wandb_init.py:init():565] run started, returning control to user process
